services:
  app:
    build: .
    container_name: my_app
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000"]

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "main_db"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:

