"""init4

Revision ID: a225c17b6a40
Revises: 993089d41e44
Create Date: 2025-03-26 16:01:47.671509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a225c17b6a40'
down_revision: Union[str, None] = '993089d41e44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_order_items_product_id_products', 'order_items', type_='foreignkey')
    op.drop_constraint('fk_order_items_order_id_orders', 'order_items', type_='foreignkey')
    op.create_foreign_key(op.f('fk_order_items_order_id_orders'), 'order_items', 'orders', ['order_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(op.f('fk_order_items_product_id_products'), 'order_items', 'products', ['product_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint('fk_orders_customer_id_customers', 'orders', type_='foreignkey')
    op.create_foreign_key(op.f('fk_orders_customer_id_customers'), 'orders', 'customers', ['customer_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_orders_customer_id_customers'), 'orders', schema='public', type_='foreignkey')
    op.create_foreign_key('fk_orders_customer_id_customers', 'orders', 'customers', ['customer_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_order_items_product_id_products'), 'order_items', schema='public', type_='foreignkey')
    op.drop_constraint(op.f('fk_order_items_order_id_orders'), 'order_items', schema='public', type_='foreignkey')
    op.create_foreign_key('fk_order_items_order_id_orders', 'order_items', 'orders', ['order_id'], ['id'])
    op.create_foreign_key('fk_order_items_product_id_products', 'order_items', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###
